### PR TITLE
Add pydocstyle pre-commit hook and configuration

### PR DESCRIPTION
**Pull request by memeplex**
image

### CODE REVIEW

**Comment by memeplex** [comment]
I've settled on google docstring style for now. Alternatively, we can go with numpy. Both styles are readable in plain text. Moreover, they are pretty well formatted if the output returned by jedi. OTOH sphinx style is hard to read in code and is returned as a "blob" (not even keeping hard breaks) by jedi. Sphinx can consume these formats using [napoleon](https://sphinxcontrib-napoleon.readthedocs.io) anyway.

**Comment by memeplex** [comment]
@tzulberti-jampp what do you think of including requirements-dev.txt? I'm unsure about some things:

1. Most of the requirements are already fetched and installed by pre-commit, although not all of them and although this doesn't cover usages other than checking pre-commit hooks, of course.
2. I dislike the idea of duplicating dev requirements both in each project and in pre-commit yaml, so with n projects we have not n dups but 2 x n.
3. In general we do explicit environment specification (concrete dependencies, optional dependencies)  in macross, while the rest of the projects specify just abstract mandatory dependencies in `install_requires` [1].

All in all I believe it's better to add the requirements-dev.txt file just to macross.

---
[1] https://packaging.python.org/discussions/install-requires-vs-requirements/ and https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by tzulberti-jampp** [comment]
> @tzulberti-jampp what do you think of including requirements-dev.txt? I'm unsure about some things:
> 
> 1. Most of the requirements are already fetched and installed by pre-commit, although not all of them and although this doesn't cover usages other than checking pre-commit hooks, of course.
> 2. I dislike the idea of duplicating dev requirements both in each project and in pre-commit yaml, so with n projects we have not n dups but 2 x n.
> 3. In general we do explicit environment specification (concrete dependencies, optional dependencies)  in macross, while the rest of the projects specify just abstract mandatory dependencies in `install_requires` [1].
> 
> All in all I believe it's better to add the requirements-dev.txt file just to macross.
> 
> [1] https://packaging.python.org/discussions/install-requires-vs-requirements/ and https://caremad.io/posts/2013/07/setup-vs-requirement/

I  think that the requirements-dev.txt is a great idea, and we are already using it for the same idea. Check the project template I proposed for tech-standardization, https://github.com/jampp/tech-standardization/tree/develop/examples/python/pytest_37_app, and it already have requirements_dev.txt. 

 It is the same standard that I am following, but the only change is that the setup.py can read that file for a specific environment: https://github.com/jampp/tech-standardization/blob/develop/examples/python/pytest_37_app/setup.py#L53

I created a PR to reneame `requirements_dev.txt` to `requirements-dev.txt` which seems to be more standard

**Comment by memeplex** [comment]
> I think that the requirements-dev.txt is a great idea

Nice, but what about putting it just in macross which is where we're putting our environmental specifications for everything else under the assumption that you're working with the "full stack"?

**Pull request merged**
